# Generated by Django 4.1.4 on 2023-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('population', models.PositiveBigIntegerField()),
                ('ruling_party', models.CharField(max_length=50)),
                ('cheif_minister', models.CharField(max_length=50)),
                ('home_minister', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('coastal', models.BooleanField()),
            ],
        ),
    ]
