# Generated by Django 4.1.4 on 2023-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='area',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='gdp',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='litreacy',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='population',
            field=models.JSONField(),
        ),
    ]
