# Generated by Django 4.1.4 on 2023-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_state_area_state_gdp_state_litreacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='litreacy',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
